#!/bin/bash

if [[ ! -z "${NVCC_PREPEND_FLAGS_BACKUP+x}" ]]
then
  export NVCC_PREPEND_FLAGS="${NVCC_PREPEND_FLAGS_BACKUP}"
  unset NVCC_PREPEND_FLAGS_BACKUP
fi

if [[ ! -z "${CFLAGS_CUDA_NVCC_BACKUP+x}" ]]
then
  export CFLAGS="${CFLAGS_CUDA_NVCC_BACKUP}"
  unset CFLAGS_CUDA_NVCC_BACKUP
fi

if [[ ! -z "${CPPFLAGS_CUDA_NVCC_BACKUP+x}" ]]
then
  export CPPFLAGS="${CPPFLAGS_CUDA_NVCC_BACKUP}"
  unset CPPFLAGS_CUDA_NVCC_BACKUP
fi

if [[ ! -z "${CXXFLAGS_CUDA_NVCC_BACKUP+x}" ]]
then
  export CXXFLAGS="${CXXFLAGS_CUDA_NVCC_BACKUP}"
  unset CXXFLAGS_CUDA_NVCC_BACKUP
fi
