#!/bin/bash

if [[ ! -z "${NVCC_PREPEND_FLAGS_BACKUP+x}" ]]
then
  export NVCC_PREPEND_FLAGS="${NVCC_PREPEND_FLAGS_BACKUP}"
  unset NVCC_PREPEND_FLAGS_BACKUP
fi

if [[ ! -z "${NVCC_APPEND_FLAGS_BACKUP+x}" ]]
then
  export NVCC_APPEND_FLAGS="${NVCC_APPEND_FLAGS_BACKUP}"
  unset NVCC_APPEND_FLAGS_BACKUP
fi

if [[ ! -z "${CUDAARCHS_BACKUP+x}" ]]
then
  export CUDAARCHS="${CUDAARCHS_BACKUP}"
  unset CUDAARCHS_BACKUP
fi

if [[ ! -z "${TORCH_CUDA_ARCH_LIST_BACKUP+x}" ]]
then
  export TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST_BACKUP}"
  unset TORCH_CUDA_ARCH_LIST_BACKUP
fi
